# Generated by Django 2.1.1 on 2018-11-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='testcase_id',
            new_name='testcase',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=0, verbose_name='status'),
        ),
    ]
