# Generated by Django 2.1.1 on 2018-11-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='testcase_id',
        ),
        migrations.AddField(
            model_name='task',
            name='cases',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='task',
            name='result',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
