# Generated by Django 2.1.1 on 2018-11-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_task_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='testcase',
        ),
        migrations.AddField(
            model_name='task',
            name='cases',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
