from .test_project_models import ProjectTestCase,moduleTestCase,VersionTestCase
from .tests_pro_mtemplate import modTemplateTestCase
from .tests_pro_ptemplate import proTemplateTestCase
from .tests_pro_views import ProViewsTestCase
from .tests_mod_views import ModViewsTestCase