# Generated by Django 2.1.1 on 2018-10-14 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=50)),
                ('createTime', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True, verbose_name='status:')),
                ('endTime', models.CharField(default='2099-12-30', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=50)),
                ('release', models.CharField(max_length=5)),
                ('createtime', models.CharField(default='', max_length=20)),
                ('endtime', models.CharField(default='2099-12-30', max_length=20)),
                ('Criticalbugs', models.CharField(default='0', max_length=20)),
                ('Majorbugs', models.CharField(default='0', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Project')),
            ],
        ),
    ]
