# Generated by Django 2.1.1 on 2018-10-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='pName',
            field=models.CharField(default='', max_length=20, verbose_name='project name'),
        ),
    ]
