# Generated by Django 2.1.1 on 2018-10-21 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_module_pname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='pName',
        ),
    ]
