# Generated by Django 2.1.1 on 2018-10-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_remove_module_pname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.CharField(max_length=20),
        ),
    ]
