# Generated by Django 2.1.1 on 2018-10-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_auto_20181029_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(max_length=50),
        ),
    ]
