# Generated by Django 2.1.1 on 2018-11-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
