# Generated by Django 2.1.1 on 2018-10-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20181002_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='version',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='version',
            name='release',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.CharField(default='', max_length=20),
        ),
    ]
