# Generated by Django 2.1.1 on 2018-10-02 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20181002_0749'),
    ]

    operations = [
    ]
