# Generated by Django 2.1.1 on 2018-10-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20181002_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='createTime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='version',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
    ]
