# Generated by Django 2.1.1 on 2018-10-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_auto_20181002_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='version',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='version',
            name='release',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.CharField(max_length=20),
        ),
    ]
