# Generated by Django 2.1.1 on 2018-10-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_auto_20181002_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='project',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
