# Generated by Django 2.1.1 on 2018-10-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='createTime',
            field=models.CharField(max_length=20),
        ),
    ]
