# Generated by Django 2.1.1 on 2018-10-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_version_createtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='endTime',
            field=models.CharField(default='2099-12-30', max_length=20),
        ),
        migrations.AddField(
            model_name='version',
            name='endtime',
            field=models.CharField(default='2099-12-30', max_length=20),
        ),
    ]
