# Generated by Django 2.1.1 on 2018-10-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_auto_20181003_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='Criticalbugs',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='version',
            name='Majorbugs',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
