# Generated by Django 2.1.1 on 2018-10-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_auto_20181004_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='Criticalbugs',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='version',
            name='Majorbugs',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
